### ISSUE TITLE
Problems building

### ISSUE THREAD

**Issue by simon-p-r** [AustinWise/SimpleDiskImager#1]
I saw this project on SmartOS mailing list, can you advise what development environment is required to build?  I can then test and provide feedback.

Thanks

**Comment by simon-p-r** [comment]
I have found releases now, Github keep moving things around

**Comment by AustinWise** [comment]
I'll update the build script and documentation to be more specific about which version to use. Also I'll add a link in the readme to the release page.

**Comment by simon-p-r** [comment]
Thanks I got it working earlier, just need to learn more about SmartOS now. I could not use ISO image supplied so used IMG file to write to USB pen instead
